import {
    AcademicCapIcon,
    BookOpenIcon,
    CalendarIcon,
    ChatIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    CogIcon,
    LibraryIcon,
    ShareIcon,
    UserGroupIcon,
    UserIcon,
} from "@heroicons/react/outline";
import Head from "next/head";
import { useState } from "react";
import Community from "../components/Community";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Login from "../components/Login";
import { auth, provider } from "../firebases";
import { actionTypes } from "../components/reducer";
import { useStateValue } from "../components/StateProvider";
import Image from "next/image";
import Academic from "../components/Academic";
import Admin from "../components/Admin";
import Chat from "../components/Chat";
import Spaces from "../components/Spaces";
import Profile from "../components/Profile";

export default function Home() {
    const [session, setSession] = useState(false);
    const [current, setCurrent] = useState("Feed");
    const [academicOption, setAcademicOption] = useState(false);
    const [drawer, setDrawer] = useState(1);
    const [{}, dispath] = useStateValue();

    function signIn() {
        // setSession(true)
        auth.signInWithPopup(provider)
            .then((result) => {
                console.log(result.user);
                dispath({
                    type: actionTypes.SET_USER,
                    user: result.user,
                });
                setSession(true);
            })
            .catch((error) => {
                alert(error.message);
            });
    }
    if (!session) return <Login signIn={signIn} />;

    return (
        <div className="bg-[#f6f9fd]  relative">
            <Head>
                <title>Sociocademy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header setCurrent={setCurrent} />
            <div className="absolute">
                <div
                    className=" p-2 z-50 mb-2 w-fit  overflow-hidden bg-white ease-in-out rounded-3xl border 
        flex space-x-3 items-center transition-all duration-500"
                >
                    {[...Array(drawer)].map((e, i) => (
                        <>
                            <div
                                className="  "
                                onClick={() => setCurrent("Feed")}
                            >
                                <img
                                    src="/socio.jpeg"
                                    className="rounded-lg border  
                h-[60px] w-[60px] p-1 object-contain"
                                />
                            </div>
                        </>
                    ))}

                    {drawer == 1 ? (
                        <ChevronRightIcon
                            onClick={() => setDrawer(3)}
                            className="h-8 cursor-pointer"
                        />
                    ) : (
                        <ChevronLeftIcon
                            onClick={() => setDrawer(1)}
                            className="h-8 cursor-pointer"
                        />
                    )}
                </div>

                <div className="   w-fit  space-y-3 h-fit pb-5">
                    <div
                        className="relative  px-3 pb-0 cursor-pointer "
                        onMouseEnter={() => setAcademicOption(true)}
                        onMouseLeave={() => setAcademicOption(false)}
                    >
                        <div className="bg-white p-2 rounded-full shadow-lg">
                            <div
                                className={`${
                                    (current == "Academic" && "bg-[#6E798C]") ||
                                    (current == "Community" && "bg-[#6E798C]")
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("Academic")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 22 18"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            (current == "Academic" &&
                                                "bg-[#6E798C]") ||
                                            current == "Community"
                                                ? "white"
                                                : "black"
                                        }
                                        d="M11 18L4 14.2V8.2L0 6L11 0L22 6V14H20V7.1L18 8.2V14.2L11 18ZM11 9.7L17.85 6L11 2.3L4.15 6L11 9.7ZM11 15.725L16 13.025V9.25L11 12L6 9.25V13.025L11 15.725Z"
                                    />
                                </svg>
                            </div>
                        </div>

                        <div
                            className={`absolute  flex-col  space-x-5 rounded-xl bg-white left-[80px]
            z-50 top-2 w-[180px] ${academicOption ? "block" : "hidden"}`}
                            onMouseLeave={() => setAcademicOption(false)}
                        >
                            <div>
                                <div
                                    onClick={() => setCurrent("Academic")}
                                    className="flex space-x-5 rounded-xl rounded-b-none
                 p-3 w-full items-center hover:bg-[#1C1F37] cursor-pointer hover:text-white"
                                >
                                    <svg
                                        width="22"
                                        height="20"
                                        viewBox="0 0 22 20"
                                        fill="none"
                                        xmlns="http://www.w3.org/2000/svg"
                                    >
                                        <path
                                            d="M1 1H7C8.06087 1 9.07828 1.42143 9.82843 2.17157C10.5786 2.92172 11 3.93913 11 5V19C11 18.2044 10.6839 17.4413 10.1213 16.8787C9.55871 16.3161 8.79565 16 8 16H1V1Z"
                                            fill="#D9D9D9"
                                            stroke="#0C0202"
                                            stroke-opacity="0.65"
                                            stroke-width="2"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        />
                                        <path
                                            d="M21 1H15C13.9391 1 12.9217 1.42143 12.1716 2.17157C11.4214 2.92172 11 3.93913 11 5V19C11 18.2044 11.3161 17.4413 11.8787 16.8787C12.4413 16.3161 13.2044 16 14 16H21V1Z"
                                            fill="#D9D9D9"
                                            stroke="#0C0202"
                                            stroke-opacity="0.65"
                                            stroke-width="2"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                        />
                                    </svg>
                                    <p>Lecture Hall</p>
                                </div>
                                <div className="flex space-x-5 hover:bg-[#1C1F37] cursor-pointer hover:text-white p-3 w-full items-center ">
                                    <UserIcon className="h-6" />
                                    <p>My Mentors</p>
                                </div>
                                <div className="flex space-x-5  p-3 w-full items-center hover:bg-[#1C1F37] cursor-pointer hover:text-white ">
                                    <BookOpenIcon className="h-7 " />
                                    <p>Library</p>
                                </div>
                                <div className="flex space-x-5  p-3 w-full items-center hover:bg-[#1C1F37] cursor-pointer hover:text-white">
                                    <svg
                                        width="25"
                                        height="22"
                                        viewBox="0 0 22 22"
                                        fill="none"
                                        xmlns="http://www.w3.org/2000/svg"
                                    >
                                        <path
                                            d="M13.4378 6.00098C16.021 6.98392 17.8564 9.48334 17.8564 12.4115C17.8564 12.7958 17.8248 13.1728 17.764 13.5399M8.56193 6.00098C5.97878 6.98392 4.14331 9.48334 4.14331 12.4115C4.14331 12.7958 4.17493 13.1728 4.23572 13.5399M15.0918 17.9137C13.9496 18.7645 12.5335 19.268 10.9999 19.268C9.46618 19.268 8.05012 18.7645 6.90796 17.9137"
                                            stroke="#A49EB5"
                                            stroke-width="1.5"
                                        />
                                        <path
                                            d="M13.4378 6.00098C16.021 6.98392 17.8564 9.48334 17.8564 12.4115C17.8564 12.7958 17.8248 13.1728 17.764 13.5399M8.56193 6.00098C5.97878 6.98392 4.14331 9.48334 4.14331 12.4115C4.14331 12.7958 4.17493 13.1728 4.23572 13.5399M15.0918 17.9137C13.9496 18.7645 12.5335 19.268 10.9999 19.268C9.46618 19.268 8.05012 18.7645 6.90796 17.9137"
                                            stroke="#333333"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="11"
                                            cy="5.34826"
                                            r="2.50316"
                                            stroke="#A49EB5"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="11"
                                            cy="5.34826"
                                            r="2.50316"
                                            stroke="#333333"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="16.9104"
                                            cy="16.0149"
                                            r="2.50316"
                                            stroke="#A49EB5"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="16.9104"
                                            cy="16.0149"
                                            r="2.50316"
                                            stroke="#333333"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="5.08641"
                                            cy="16.0149"
                                            r="2.50316"
                                            stroke="#A49EB5"
                                            stroke-width="1.5"
                                        />
                                        <circle
                                            cx="5.08641"
                                            cy="16.0149"
                                            r="2.50316"
                                            stroke="#333333"
                                            stroke-width="1.5"
                                        />
                                    </svg>

                                    <p>Clubs</p>
                                </div>
                                <div
                                    onClick={() => setCurrent("Community")}
                                    className="flex space-x-5  p-3 w-full items-center hover:bg-[#1C1F37] cursor-pointer hover:text-white"
                                >
                                    <svg
                                        width="20"
                                        height="22"
                                        viewBox="0 0 20 22"
                                        fill="none"
                                        xmlns="http://www.w3.org/2000/svg"
                                    >
                                        <g clip-path="url(#clip0_218_1255)">
                                            <path
                                                d="M16.6666 6.41675H3.33329C2.41282 6.41675 1.66663 7.23756 1.66663 8.25008V18.3334C1.66663 19.3459 2.41282 20.1667 3.33329 20.1667H16.6666C17.5871 20.1667 18.3333 19.3459 18.3333 18.3334V8.25008C18.3333 7.23756 17.5871 6.41675 16.6666 6.41675Z"
                                                stroke="#332F2F"
                                                stroke-opacity="0.8"
                                                stroke-width="2"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                            />
                                            <path
                                                d="M14.1667 1.83325L10 6.41659L5.83337 1.83325"
                                                stroke="#332F2F"
                                                stroke-opacity="0.8"
                                                stroke-width="2"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                            />
                                        </g>
                                        <defs>
                                            <clipPath id="clip0_218_1255">
                                                <rect
                                                    width="20"
                                                    height="22"
                                                    fill="white"
                                                />
                                            </clipPath>
                                        </defs>
                                    </svg>
                                    <p>My Learning</p>
                                </div>
                                <div
                                    className="flex space-x-5
                rounded-b-xl  p-3 w-full items-center hover:bg-[#1C1F37] cursor-pointer hover:text-white"
                                >
                                    <CogIcon className="h-7 " />
                                    <p>Maker Space</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="relative  px-3 pb-0 cursor-pointer ">
                        <div className="bg-white p-2 rounded-full shadow-2xl">
                            <div
                                className={`${
                                    current == "Chat" && "bg-[#6E798C]"
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("Chat")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 20 20"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            current == "Chat"
                                                ? "white"
                                                : "black"
                                        }
                                        d="M4 12H12V10H4V12ZM4 9H16V7H4V9ZM4 6H16V4H4V6ZM0 20V2C0 1.45 0.196 0.979 0.588 0.587C0.979333 0.195667 1.45 0 2 0H18C18.55 0 19.021 0.195667 19.413 0.587C19.8043 0.979 20 1.45 20 2V14C20 14.55 19.8043 15.021 19.413 15.413C19.021 15.8043 18.55 16 18 16H4L0 20ZM2 15.175L3.175 14H18V2H2V15.175Z"
                                    />
                                </svg>
                            </div>
                        </div>
                    </div>

                    <div className="relative  px-3 pb-0 cursor-pointer ">
                        <div className="bg-white p-2 rounded-full shadow-lg">
                            <div
                                className={`${
                                    current == "1" && "bg-[#6E798C]"
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("1")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 20 20"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            current == "1" ? "white" : "black"
                                        }
                                        d="M12.7778 16C12 16 11.3426 15.7583 10.8056 15.275C10.2685 14.7917 10 14.2 10 13.5C10 12.8 10.2685 12.2083 10.8056 11.725C11.3426 11.2417 12 11 12.7778 11C13.5556 11 14.213 11.2417 14.75 11.725C15.287 12.2083 15.5556 12.8 15.5556 13.5C15.5556 14.2 15.287 14.7917 14.75 15.275C14.213 15.7583 13.5556 16 12.7778 16ZM2.22222 20C1.61111 20 1.08778 19.8043 0.652222 19.413C0.217407 19.021 0 18.55 0 18V4C0 3.45 0.217407 2.97933 0.652222 2.588C1.08778 2.196 1.61111 2 2.22222 2H3.33333V0H5.55556V2H14.4444V0H16.6667V2H17.7778C18.3889 2 18.9122 2.196 19.3478 2.588C19.7826 2.97933 20 3.45 20 4V18C20 18.55 19.7826 19.021 19.3478 19.413C18.9122 19.8043 18.3889 20 17.7778 20H2.22222ZM2.22222 18H17.7778V8H2.22222V18ZM2.22222 6H17.7778V4H2.22222V6Z"
                                    />
                                </svg>
                            </div>
                        </div>
                    </div>

                    <div className="relative  px-3 pb-0 cursor-pointer ">
                        <div className="bg-white p-2 rounded-full shadow-lg">
                            <div
                                className={`${
                                    current == "2" && "bg-[#6E798C]"
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("2")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 20 20"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            current == "2" ? "white" : "black"
                                        }
                                        d="M14.2426 0H5.75745C4.23045 0 2.766 0.606539 1.68627 1.68627C0.606539 2.766 0 4.2305 0 5.75745V14.2426C0 15.7696 0.606539 17.234 1.68627 18.3137C2.766 19.3935 4.2305 20 5.75745 20H14.2426C15.7696 20 17.234 19.3935 18.3137 18.3137C19.3935 17.234 20 15.7695 20 14.2426V5.75745C20 4.23045 19.3935 2.766 18.3137 1.68627C17.234 0.606539 15.7695 0 14.2426 0V0ZM5.75797 1.81816H14.2426C15.2864 1.82141 16.2864 2.23739 17.0246 2.9754C17.7626 3.71362 18.1786 4.71361 18.1818 5.75745V6.0604L2.12122 6.06061C2.01733 6.06203 1.91465 6.08252 1.81827 6.12108V5.75745C1.82151 4.71361 2.2375 3.71362 2.9755 2.9754C3.71373 2.23738 4.71372 1.82138 5.75755 1.81816L5.75797 1.81816ZM12.1215 18.1816H7.87909V13.9392H12.1215V18.1816ZM12.1215 12.1209H7.87909V7.87846H12.1215V12.1209ZM1.81827 7.818C1.91466 7.85655 2.01733 7.87705 2.12122 7.87867H6.06072V12.1211L2.12122 12.1209C2.01733 12.1225 1.91465 12.143 1.81827 12.1816V7.818ZM1.81827 14.2423V13.8787C1.91466 13.9173 2.01733 13.9378 2.12122 13.9392H6.06072V18.1816H5.75756C4.71372 18.1784 3.71373 17.7624 2.97551 17.0244C2.23749 16.2862 1.82149 15.2862 1.81827 14.2424L1.81827 14.2423ZM14.2426 18.1816H13.9396V7.87888H18.182L18.1818 14.2424C18.1786 15.2863 17.7626 16.2863 17.0246 17.0245C16.2864 17.7625 15.2864 18.1785 14.2426 18.1817L14.2426 18.1816Z"
                                    />
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="relative  px-3 pb-0 cursor-pointer ">
                        <div className="bg-white p-2 rounded-full shadow-lg">
                            <div
                                className={`${
                                    current == "Spaces" && "bg-[#6E798C]"
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("Spaces")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 22 19"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        fill-rule="evenodd"
                                        clip-rule="evenodd"
                                        d="M7.25 3.75C7.25 1.67893 8.92893 0 11 0C13.0711 0 14.75 1.67893 14.75 3.75C14.75 5.82107 13.0711 7.5 11 7.5C8.92893 7.5 7.25 5.82107 7.25 3.75Z"
                                    />
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        fill-rule="evenodd"
                                        clip-rule="evenodd"
                                        d="M14.75 6.75C14.75 5.09315 16.0931 3.75 17.75 3.75C19.4069 3.75 20.75 5.09315 20.75 6.75C20.75 8.40685 19.4069 9.75 17.75 9.75C16.0931 9.75 14.75 8.40685 14.75 6.75Z"
                                    />
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        fill-rule="evenodd"
                                        clip-rule="evenodd"
                                        d="M1.25 6.75C1.25 5.09315 2.59315 3.75 4.25 3.75C5.90685 3.75 7.25 5.09315 7.25 6.75C7.25 8.40685 5.90685 9.75 4.25 9.75C2.59315 9.75 1.25 8.40685 1.25 6.75Z"
                                    />
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        fill-rule="evenodd"
                                        clip-rule="evenodd"
                                        d="M5.30986 12.1175C6.50783 10.2444 8.60835 9 11 9C13.3919 9 15.4927 10.2447 16.6906 12.1182C17.5187 13.4134 17.877 14.9752 17.709 16.4979C17.6827 16.7359 17.5444 16.947 17.3368 17.0662C15.4694 18.1376 13.3051 18.75 11 18.75C8.69492 18.75 6.53059 18.1376 4.66325 17.0662C4.45559 16.947 4.3173 16.7359 4.29103 16.4979C4.12293 14.9749 4.48141 13.4129 5.30986 12.1175Z"
                                    />
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        d="M4.08228 11.2537C4.07024 11.2722 4.05827 11.2907 4.04638 11.3093C3.08091 12.8189 2.63908 14.6167 2.77471 16.389C2.16667 16.2967 1.5767 16.1481 1.01043 15.9487L0.89547 15.9082C0.685759 15.8343 0.539227 15.6439 0.521591 15.4222L0.511923 15.3007C0.504017 15.2014 0.5 15.1011 0.5 15C0.5 12.9851 2.08905 11.3414 4.08228 11.2537Z"
                                    />
                                    <path
                                        fill={
                                            current == "Spaces"
                                                ? "white"
                                                : "black"
                                        }
                                        d="M19.2256 16.389C19.3612 14.617 18.9196 12.8196 17.9545 11.3102C17.9424 11.2913 17.9303 11.2725 17.9181 11.2537C19.9111 11.3416 21.5 12.9853 21.5 15C21.5 15.1011 21.496 15.2014 21.4881 15.3007L21.4784 15.4222C21.4608 15.6439 21.3142 15.8343 21.1045 15.9082L20.9896 15.9487C20.4234 16.1481 19.8336 16.2966 19.2256 16.389Z"
                                    />
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="relative  px-3 pb-0 cursor-pointer ">
                        <div className="bg-white p-2 rounded-full shadow-lg">
                            <div
                                className={`${
                                    current == "3" && "bg-[#6E798C]"
                                } rounded-full p-2 text-white`}
                                onClick={() => setCurrent("3")}
                            >
                                <svg
                                    width="28"
                                    height="25"
                                    viewBox="0 0 15 20"
                                    fill="none"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        fill={
                                            current == "3" ? "white" : "black"
                                        }
                                        d="M7.25 20C6.81667 20 6.425 19.896 6.075 19.688C5.725 19.4793 5.45 19.2 5.25 18.85C4.7 18.85 4.22933 18.6543 3.838 18.263C3.446 17.871 3.25 17.4 3.25 16.85V13.3C2.26667 12.65 1.47933 11.7917 0.888 10.725C0.296 9.65833 0 8.5 0 7.25C0 5.23333 0.704 3.52067 2.112 2.112C3.52067 0.704 5.23333 0 7.25 0C9.26667 0 10.979 0.704 12.387 2.112C13.7957 3.52067 14.5 5.23333 14.5 7.25C14.5 8.53333 14.2043 9.7 13.613 10.75C13.021 11.8 12.2333 12.65 11.25 13.3V16.85C11.25 17.4 11.0543 17.871 10.663 18.263C10.271 18.6543 9.8 18.85 9.25 18.85C9.05 19.2 8.775 19.4793 8.425 19.688C8.075 19.896 7.68333 20 7.25 20ZM5.25 16.85H9.25V15.95H5.25V16.85ZM5.25 14.95H9.25V14H5.25V14.95ZM5.05 12H6.5V9.3L4.3 7.1L5.35 6.05L7.25 7.95L9.15 6.05L10.2 7.1L8 9.3V12H9.45C10.35 11.5667 11.0833 10.929 11.65 10.087C12.2167 9.24567 12.5 8.3 12.5 7.25C12.5 5.78333 11.9917 4.54167 10.975 3.525C9.95833 2.50833 8.71667 2 7.25 2C5.78333 2 4.54167 2.50833 3.525 3.525C2.50833 4.54167 2 5.78333 2 7.25C2 8.3 2.28333 9.24567 2.85 10.087C3.41667 10.929 4.15 11.5667 5.05 12Z"
                                    />
                                </svg>
                            </div>
                        </div>
                    </div>
                    {/* <div className='relative  px-3 pb-0 cursor-pointer '>
            <div className='bg-white p-2 rounded-full shadow-lg'>
              <div className={`${current == "4" && "bg-[#6E798C]"} rounded-full p-2 text-white`} onClick={() => setCurrent('4')}>



              </div>
            </div>
          </div> */}
                    {/* <div className='p-3 cursor-pointer'>
            <svg width="30" height="35" onClick={() => setCurrent('Admin')} viewBox="0 0 22 22" fill="black" xmlns="http://www.w3.org/2000/svg">
              <path d="M12.7013 5.33489C12.5181 5.52182 12.4155 5.77314 12.4155 6.03489C12.4155 6.29664 12.5181 6.54796 12.7013 6.73489L14.3013 8.33489C14.4882 8.51812 14.7396 8.62075 15.0013 8.62075C15.2631 8.62075 15.5144 8.51812 15.7013 8.33489L19.4713 4.56489C19.9742 5.67608 20.1264 6.91413 19.9078 8.11404C19.6892 9.31395 19.11 10.4187 18.2476 11.2812C17.3852 12.1436 16.2804 12.7227 15.0805 12.9413C13.8806 13.16 12.6425 13.0077 11.5313 12.5049L4.62132 19.4149C4.2235 19.8127 3.68393 20.0362 3.12132 20.0362C2.55871 20.0362 2.01914 19.8127 1.62132 19.4149C1.2235 19.0171 1 18.4775 1 17.9149C1 17.3523 1.2235 16.8127 1.62132 16.4149L8.53132 9.50489C8.02848 8.3937 7.87624 7.15566 8.09486 5.95575C8.31349 4.75584 8.89261 3.65105 9.75504 2.78861C10.6175 1.92618 11.7223 1.34706 12.9222 1.12843C14.1221 0.909808 15.3601 1.06206 16.4713 1.56489L12.7013 5.33489Z" stroke="#FDFDFD" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>

          </div> */}
                </div>
            </div>
            {/* <Feed /> */}
            {
                {
                    Feed: <Feed />,
                    Academic: <Academic />,
                    Community: <Community />,
                    // 'Admin': <Admin />,
                    Chat: <Chat />,
                    Spaces: <Spaces />,
                    Profile: <Profile />,
                }[current]
            }
        </div>
    );
}
