import { AcademicCapIcon, BookOpenIcon, CalendarIcon, ChatIcon, LibraryIcon, ShareIcon, UserGroupIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import { useState } from 'react'
import Community from '../components/Community'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Login from '../components/Login'
import { auth, provider } from '../firebase'
import { actionTypes } from '../components/reducer'
import { useStateValue } from '../components/StateProvider'


export default function Home() {
  const [session, setSession] = useState(false)
  const [current, setCurrent] = useState('Academic')
  const [{ }, dispath] = useStateValue();


  function signIn() {

    setSession(true)
    // auth.signInWithPopup(provider).then(result => {
    //   dispath({
    //     type: actionTypes.SET_USER,
    //     user: result.user
    //   })

    // }).catch(error => {
    //   alert(error.message)
    // });
  }
  if (!session) return <Login signIn={signIn} />



  return (
    <div className='bg-[#f6f9fd]  relative'>
      <Head>
        <title>Sociocademy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className='absolute bg-[#f9f1f0] max-w-fit p-3 space-y-8 h-[100vh]'>
        <AcademicCapIcon className='h-7' onClick={() => setCurrent('Academic')} />
        <ChatIcon className='h-7 ' />
        <CalendarIcon className='h-12 p-2
         text-white rounded-full bg-[#6E798C]' />
        <UserGroupIcon className='h-7 ' onClick={() => setCurrent('Community')} />
        <ShareIcon className='h-7 ' />
        <BookOpenIcon className='h-7 ' />
      </div>
      {/* <Feed /> */}
      {
        {
          'Academic': <Feed />,
          'Community': <Community />,

        }[current]
      }

    </div >
  )
}
